In [2]:
import numpy as np

In [42]:
# Here array like Array in c++ ,not like vector , so every row has same data

arr1=np.array([10,20,40])
print(arr1)
print(arr1.shape)
print(arr1.sum())
print(arr1.mean().round())
print(arr1.std().round())
print(arr1.var().round())
print(np.median(arr1).round())

[10 20 40]
(3,)
70
23.0
12.0
156.0
20.0


In [25]:
arr2=np.eye(3,dtype=np.int64)
print(arr2)
print(arr2.dtype)
arr3=np.ones((2,6),dtype=int) # give in float by default
print(arr3)
arr4=np.zeros((3,4),dtype=int)
print(arr4)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
int64
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [33]:

arr5=np.arange(1,12,2).reshape((2,3))
print(arr5)


[[ 1  3  5]
 [ 7  9 11]]


In [35]:

arr6=np.array([10,20,30,40])
arr7=np.array([1,2,3,4])

print(arr6+arr7)
print(arr6-arr7)
print(arr6*arr7)
print(arr6//arr7)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10 10 10 10]


In [38]:
arr8=np.array([[5,4],[2,4]])
arr9=np.array([[5,4]])

print(arr8+arr9)

[[10  8]
 [ 7  8]]


In [39]:

arr10=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr10))

## Exponential
print(np.exp(arr10))

## Sine
print(np.sin(arr10))

## natural log
print(np.log(arr10))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [46]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data)
new_data=data[(data>=5) & (data<=8)]
print(new_data)


[ 1  2  3  4  5  6  7  8  9 10]
[5 6 7 8]


In [53]:

# Slicing
arr11=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr11,end="\n \n")

arr12=arr11[1:,1:3]
print("New Array \n",arr12)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
New Array 
 [[ 6  7]
 [10 11]]
